### ISSUE TITLE
staking dashboard setup for tanganika parachain

### ISSUE THREAD

**Issue by happyJ2024** [web3go-xyz/web3go.xyz#126]
the RPC for Data highway: wss://tanganika-archive.datahighway.com/

**Comment by happyJ2024** [comment]
preview: 
https://dev-v2.web3go.xyz:10005/#/DataHighwayStaking

**Comment by happyJ2024** [comment]
difference doc: 
https://www.notion.so/web3go/Tanganika-Kusama-347de4fc2b1442a892ee1a8bea673654

**Comment by happyJ2024** [comment]
tasks left:
1.  delgate function
2.  unstake function

**Comment by imqipan** [comment]
Finished but: 
Some features are under testing, Unstake, etc. The Unstake will take 7 days before we can really operate it. 
Some roundabouts are under verifying due to a lack of the APIs/data, such as the showing MyStake button during the Unstake window. It would exclude the nominator from the delegations once we request for Unstake, and it only allowed one Stake at the same time, so it requires relatively real-time data to be fetched from the indexer service where the lost collator-delegator relation is currently acquired.
