### ISSUE TITLE
MoonPush:  support user to customize the message content for pre-defined variables

### ISSUE THREAD

**Issue by bianyunjian** [web3go-xyz/web3go.xyz#69]
![image](https://user-images.githubusercontent.com/12878885/166180374-f387c14b-9a51-47db-9d22-920237a38c68.png)

current:
the message is formatted by JSON, and send like this:
![image](https://user-images.githubusercontent.com/12878885/166180427-b79ea97c-f14b-43fc-95f2-3ff62070c8a1.png)
![image](https://user-images.githubusercontent.com/12878885/166180439-9983320e-7d8c-4032-ba0e-064aa05215bc.png)

this is more like a  program message from internal system.
user will need a more readable message content.

requirement:
 we could build a message formatter to

- [ ]  provide a list of variables pre-defined,   ${xx}  format are prefered.
- [ ]   user can place these variables in their message contents.
- [ ]   the formatter will parse and replace the variables with real value, before sending the notify messages.

some codes:
notify-service/src/notify-process/notify-worker/notify.formater.ts

**Comment by rachaelyychen** [comment]
## New Interfaces of Trigger Script Template Manage

**1. create or update trigger script template**

POST {HOST}/api/v1/script-template-manage/createScriptTemplate

```
{
  "id": 0,
  "trigger_type": "wallet_monitor",
  "script_template": "THIS IS SCRIPT",
  "variables": [
    {
      "variable_name": "chain",
      "variable_desc": "chain name"
    }
  ]
}
```

`id` equaled 0 means create, otherwise update.
`trigger_type` is wallet_monitor/ gas/ anyswap/ dex.
`script_template` is the script code.
`variables` is a collection of result variables returned by trigger script execution. 

**2. get trigger script templates with variables**

POST {HOST}/api/v1/script-template-manage/getScriptTemplates

```
{
  "trigger_type": "wallet_monitor"
}
```

`trigger_type` is wallet_monitor/ gas/ anyswap/ dex.

**Comment by rachaelyychen** [comment]
sql query for update table `smart_trigger_script ` column `script_template_id` according to table `script_template`:

update smart_trigger_script
set script_template_id = e.script_template_id
from 
(select d.id as script_template_id, c.trigger_script_id as trigger_script_id from script_template d
left join (select a.trigger_type as trigger_type, b.id as trigger_script_id from smart_trigger a LEFT JOIN smart_trigger_script b on a.id = b.trigger_id) c
on d.trigger_type = c.trigger_type) e
where id = e.trigger_script_id
